

import com.ozten.font.JFontChooser;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class mainFarme extends javax.swing.JFrame {

    /**
     * Creates new form mainFarme
     */
    private boolean isSave=false;
    public mainFarme() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnCoppy = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcontent = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbfile = new javax.swing.JMenu();
        mbnew = new javax.swing.JMenuItem();
        mbopen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mbexit = new javax.swing.JMenuItem();
        mbedit = new javax.swing.JMenu();
        mbformat = new javax.swing.JMenu();
        mbfind = new javax.swing.JMenuItem();
        miFont = new javax.swing.JMenuItem();

        mnCoppy.setText("Coppy");
        mnCoppy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCoppyActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnCoppy);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcontent.setColumns(20);
        txtcontent.setRows(5);
        txtcontent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtcontentMouseReleased(evt);
            }
        });
        txtcontent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcontentKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtcontent);

        mbfile.setText("File");

        mbnew.setText("New");
        mbnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbnewActionPerformed(evt);
            }
        });
        mbfile.add(mbnew);

        mbopen.setText("Open");
        mbopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbopenActionPerformed(evt);
            }
        });
        mbfile.add(mbopen);
        mbfile.add(jSeparator1);

        mbexit.setText("Exit");
        mbfile.add(mbexit);

        jMenuBar1.add(mbfile);

        mbedit.setText("Edit");
        jMenuBar1.add(mbedit);

        mbformat.setText("Format");
        mbformat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbformatActionPerformed(evt);
            }
        });

        mbfind.setText("Find");
        mbfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbfindActionPerformed(evt);
            }
        });
        mbformat.add(mbfind);

        miFont.setText("Font");
        miFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFontActionPerformed(evt);
            }
        });
        mbformat.add(miFont);

        jMenuBar1.add(mbformat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCoppyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCoppyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCoppyActionPerformed

    private void mbnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbnewActionPerformed
        // TODO add your handling code here:
        String s = txtcontent.getText();
        if(isSave)
            SaveFile();
        txtcontent.setText("");
    }//GEN-LAST:event_mbnewActionPerformed

    public void SaveFile()
    {
        int ans=JOptionPane.showConfirmDialog(null, "Do you want to save", "warring", JOptionPane.YES_NO_OPTION);
        if(ans==JOptionPane.YES_OPTION)
        {
            JFileChooser fc= new JFileChooser();
            int result = fc.showSaveDialog(null);
            if(result==JFileChooser.APPROVE_OPTION)
            {
                try{
                String s = txtcontent.getText();
                File f = fc.getSelectedFile();// lay fle user nhap ten
                PrintWriter w = new PrintWriter(f);
                w.print(s);
                w.flush();
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                
            }
        }
    }
    private void txtcontentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontentKeyReleased
        // TODO add your handling code here:
        isSave=true;
    }//GEN-LAST:event_txtcontentKeyReleased
public void OpenFile()
{
    JFileChooser fc = new JFileChooser();
    int result = fc.showOpenDialog(null);
    if(result==JFileChooser.APPROVE_OPTION)
    {
        try {
            File f = fc.getSelectedFile();
            FileReader fr = new FileReader(f);
            BufferedReader r = new BufferedReader(fr);
            txtcontent.setText("");
            while(r.ready())
            {
                txtcontent.setText(txtcontent.getText()+r.readLine());
            }
            if(r!=null)
            r.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
    private void mbopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbopenActionPerformed
        // TODO add your handling code here:
        if(isSave)
            SaveFile();
        OpenFile();
    }//GEN-LAST:event_mbopenActionPerformed

    private void mbformatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbformatActionPerformed
        // TODO add your handling code here:
          
     
    }//GEN-LAST:event_mbformatActionPerformed

    private void mbfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbfindActionPerformed
        // TODO add your handling code here:
        txtcontent.select(0,10);
        
    }//GEN-LAST:event_mbfindActionPerformed

    private void miFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFontActionPerformed
        // TODO add your handling code here:
         Font f = JFontChooser.showDialog(this, "choose a font", "ok");
        if(f!=null)
        txtcontent.setFont(f);
    }//GEN-LAST:event_miFontActionPerformed

    private void txtcontentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontentMouseReleased
      int x= evt.getXOnScreen();
      int y = evt.getYOnScreen();
      if(evt.getButton()==3)
      {
          jPopupMenu1.setLocation(x, y);
          jPopupMenu1.setVisible(true);
      }
    }//GEN-LAST:event_txtcontentMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFarme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFarme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mbedit;
    private javax.swing.JMenuItem mbexit;
    private javax.swing.JMenu mbfile;
    private javax.swing.JMenuItem mbfind;
    private javax.swing.JMenu mbformat;
    private javax.swing.JMenuItem mbnew;
    private javax.swing.JMenuItem mbopen;
    private javax.swing.JMenuItem miFont;
    private javax.swing.JMenuItem mnCoppy;
    private javax.swing.JTextArea txtcontent;
    // End of variables declaration//GEN-END:variables
}
